// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgJOa_8M2ov_lBUhuIx75bJK8wVmWnDYg',
    appId: '1:96388064144:web:e0b89e0be76e74ff590915',
    messagingSenderId: '96388064144',
    projectId: 'runmate-6fa65',
    authDomain: 'runmate-6fa65.firebaseapp.com',
    storageBucket: 'runmate-6fa65.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgwdSdbJ7p4qG-Hf0vJzG9FTIYUNSaJ4s',
    appId: '1:96388064144:android:d6a6d01bf269ea66590915',
    messagingSenderId: '96388064144',
    projectId: 'runmate-6fa65',
    storageBucket: 'runmate-6fa65.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANAMzAaFcPsMda4IdbmgrNCySbdZlBD50',
    appId: '1:96388064144:ios:0b84cc0c2d757f11590915',
    messagingSenderId: '96388064144',
    projectId: 'runmate-6fa65',
    storageBucket: 'runmate-6fa65.firebasestorage.app',
    iosClientId: '96388064144-j0tmd9f25n238g8hf123tn0iq0nhaog7.apps.googleusercontent.com',
    iosBundleId: 'com.example.runmateApp',
  );

}